### PR TITLE
Testing pull

### PR DESCRIPTION
**Pull request by rfortunatov**
`rf` review

### CODE REVIEW

**Comment by rfortunatov-softheme** [comment]
<a href="http://teamcity/viewType.html?buildTypeId=AppAssure_Windows_FeatureBuilds_PhantomStorageLayer_FullBuild&guest=1">

</a>

**Comment by rfortunatov-softheme** [comment]
<a href="http://tc.appassure.com/teamcity/viewType.html?buildTypeId=AppAssure_Windows_FeatureBuilds_PhantomStorageLayer_FullBuild&guest=1">

</a>

**Comment by rfortunatov-softheme** [comment]
<a href="https://tc.appassure.com/teamcity/viewType.html?buildTypeId=AppAssure_Windows_FeatureBuilds_PhantomStorageLayer_FullBuild&guest=1">

</a>

**Comment by rfortunatov-softheme** [comment]
<a href="https://tc.appassure.com/viewType.html?buildTypeId=AppAssure_Windows_FeatureBuilds_PhantomStorageLayer_FullBuild&guest=1">

</a>

**Comment by rfortunatov** [comment]
[ftr](https://www8.v1host.com/AppAssureSoftwareInc/defect.mvc/Summary?oidToken=Defect%3A461942)

**Pull request closed without merging**
